name: build

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: setup env
              run: |
                  sudo apt-get update && sudo apt-get install -y clang lld
                  cd ${{ github.workspace }}
                  curl -L -o toolchain-llvm-18.tar.gz https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.4/toolchain-llvm-18.tar.gz
                  tar -xf ${{ github.workspace }}/toolchain-llvm-18.tar.gz

            - name: checkout
              uses: actions/checkout@v7
              with:
                  path: "OpenOrbis/PS4Toolchain/samples/main"

            - name: build
              run: |
                  echo "OO_PS4_TOOLCHAIN=${{ github.workspace }}/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV
                  echo "${{ github.workspace }}/OpenOrbis/PS4Toolchain/bin" >> $GITHUB_PATH
                  cd OpenOrbis/PS4Toolchain/samples/main
                  make

            - name: make pkg
              run: |
                  #make pkg

            - name: publish
              uses: actions/upload-artifact@v4
              with:
                  name: dists
                  path: |
                      */*.pkg
                      */eboot.bin
                  if-no-files-found: warn
