name: build

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v7

            - name: OpenOrbis
              uses: dawidd6/action-download-release@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  owner: OpenOrbis
                  repo: OpenOrbis-PS4-Toolchain
                  tag: "v0.5.4"
                  file: "toolchain-llvm-18.tar.gz"
                  dir: "${{ github.workspace }}/toolchain"

            - name: toolchain env
              run: |
                  tar -xzf ${{ github.workspace }}/toolchain/toolchain-llvm-18.tar.gz -C ${{ github.workspace }}/toolchain
                  echo "OO_PS4_TOOLCHAIN=${{ github.workspace }}/toolchain" >> $GITHUB_ENV
                  echo "${{ github.workspace }}/toolchain/bin" >> $GITHUB_PATH

            - name: make
              run: |
                  cd hello_world
                  make

            - name: make pkg
              run: |
                  make pkg

            - name: publish
              uses: actions/upload-artifact@v4
              with:
                  name: dists
                  path: |
                      */*.pkg
                      */eboot.bin
                  if-no-files-found: warn
